// This file generated by ngrestcg
// For more information, please visit: https://github.com/loentar/ngrest

#ifndef API_H
#define API_H

#include <ngrest/common/Service.h>

#include <string>
#include <map>

// *location: api
struct Icon {
    std::string icon;
    std::string text;
};

struct MessagesGeneral {
    Icon IOError;
    Icon serverError;
    Icon tryConnect;
    Icon testIO;
};

struct MessagesEntry {
    Icon clearedToGo;
    Icon empty;
    Icon invalid;
    Icon pressButton;
    Icon removeTicket;
    Icon validateTicket;
    Icon welcome;
    Icon parkingFull;
};

struct MessagesExit {
    Icon clearedToGo;
    Icon empty;
    Icon errorReadingCard;
    Icon goToAdministration;
    Icon insertCard;
    Icon nonAuthorized;
    Icon validateTicket;
    Icon vehicleDoesntMatch;
};

struct Config {
    std::string type;
    std::string clientCode;
    std::string address;
    std::string interphoneIP;
    std::string codeCardFormat;
    std::string paperSensor;
    std::string openedGateSensor;
    std::string closedGateSensor;
    std::string automaticCarCharging;
    std::string automaticMotoCharging;
    std::string activateEquipment;
    std::string fullCourtyard;
    std::string accessControl;
    std::string expansionPort;
    std::string rfidPort;
    std::string barcodePort;
    std::string printerPort;
    std::string useDefaultIcons;
    std::string adCount;
    std::string adOne;
    std::string adTwo;
    std::string adThree;
    std::string adFour;
    std::string adFive;
    std::string adSix;
    std::string adSeven;
    std::string adEight;
    std::string adNine;
    std::string adTen;
    MessagesGeneral messagesGeneral;
    MessagesEntry messagesEntry;
    MessagesExit messagesExit;
};

struct Response {
    bool success;
    std::string message;
};

class api: public ngrest::Service
{
public:
    // *method: POST
    // *location: /update
    Response updateConfig(std::string token, Config config);

    // *method: POST
    // *location: /get
    Config getConfig(std::string token);
};

#endif // API_H



